name: python test mlops

on:
  push: 
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:   
        working-directory: ./

    strategy:
      matrix:
        python-packages: [3.9]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: testing
        run: |
            make install 
            make test

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t abdulwadood39/mlops-repo-test:latest .
          docker push abdulwadood39/mlops-repo-test:latest


